# Streamlit এর জন্য আলাদা Dockerfile
FROM python:3.11.9-slim

WORKDIR /app

# শুধু দরকারি packages
RUN pip install streamlit requests

COPY streamlit_app.py .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0"]